/*
 * Builds the browser harness, and — in watch mode — the plugin alongside it.
 *
 * Both bundles are built from the same source files. There is no copy of the
 * dice engine, the settings or the stylesheet, so "change one thing and it
 * changes for both" is structural rather than a convention anyone has to keep.
 *
 *   node esbuild.harness.mjs          build harness/harness.js once
 *   node esbuild.harness.mjs serve    watch both, serve the harness
 */

import esbuild from 'esbuild';
import process from 'process';
import http from 'http';
import fs from 'fs';
import path from 'path';

const serve = process.argv[2] === 'serve';
const PORT = Number(process.env.HARNESS_PORT || 8732);

/**
 * The harness imports the plugin, which imports 'obsidian'. There is no
 * obsidian outside the app, so point that name at the stub. tsc still resolves
 * the real obsidian types, so everything is type-checked against reality — only
 * the runtime is swapped.
 */
const harnessConfig = {
    entryPoints: ['harness/main.ts'],
    bundle: true,
    outfile: 'harness/harness.js',
    format: 'iife',
    target: 'es2018',
    platform: 'browser',
    sourcemap: 'inline',
    logLevel: 'info',
    alias: {
        obsidian: './harness/obsidian-stub.ts'
    },
    banner: {
        js: '/* Generated by esbuild.harness.mjs — do not edit. Source: harness/*.ts + the plugin. */'
    }
};

/** Same output Obsidian loads, so the vault stays current while iterating. */
const pluginConfig = {
    entryPoints: ['main.ts'],
    bundle: true,
    outfile: 'main.js',
    format: 'cjs',
    target: 'es2018',
    external: ['obsidian', 'electron'],
    sourcemap: 'inline',
    logLevel: 'info',
    treeShaking: true
};

if (!serve) {
    await esbuild.build(harnessConfig);
    process.exit(0);
}

const harnessCtx = await esbuild.context(harnessConfig);
const pluginCtx = await esbuild.context(pluginConfig);
await harnessCtx.watch();
await pluginCtx.watch();

const MIME = {
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.png': 'image/png',
    '.svg': 'image/svg+xml',
    '.map': 'application/json'
};

const ROOT = process.cwd();

http.createServer((req, res) => {
    const url = decodeURIComponent((req.url || '/').split('?')[0]);

    // The page lives at /harness/ rather than / so that its own relative URLs
    // resolve: ./harness.css stays inside harness/, and ../styles.css reaches
    // the plugin's real stylesheet at the root.
    if (url === '/' || url === '/harness') {
        res.writeHead(302, { Location: '/harness/' }).end();
        return;
    }

    const target = url === '/harness/' ? '/harness/index.html' : url;

    // Serve from the plugin root so ../styles.css resolves from harness/.
    const filePath = path.join(ROOT, target);
    if (!filePath.startsWith(ROOT)) {
        res.writeHead(403).end('forbidden');
        return;
    }

    fs.readFile(filePath, (err, data) => {
        if (err) {
            res.writeHead(404, { 'Content-Type': 'text/plain' }).end(`not found: ${target}`);
            return;
        }
        res.writeHead(200, {
            'Content-Type': MIME[path.extname(filePath)] || 'application/octet-stream',
            // Always fetch the freshest build; this is a dev server.
            'Cache-Control': 'no-store'
        });
        res.end(data);
    });
}).listen(PORT, '127.0.0.1', () => {
    console.log(`\n  harness  http://localhost:${PORT}/`);
    console.log('  watching harness/*.ts and the plugin — both rebuild on save.');
    console.log('  reload the page to pick up a rebuild.\n');
});
